## Global redirects

# Remove direct references to index.html.
# Concrete Example: /foo/bar/index.html /foo/bar/ 301!

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/*/index.html"
  to = "/:splat/"
  status = 301
  force = true


## Single page redirects

[[redirects]]
  from = "/tdee/"
  to = "/calorie-targets/"
  status = 301
  force = true